# Generated by Django 4.2.20 on 2025-05-13 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категория')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название игрушки')),
                ('height', models.CharField(max_length=50, verbose_name='Высота')),
                ('design', models.CharField(max_length=100, verbose_name='Дизайн')),
                ('material', models.CharField(max_length=100, verbose_name='Материал')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.FileField(upload_to='toys/', verbose_name='Изображение')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toys.category', verbose_name='Категория')),
            ],
        ),
    ]
